### ISSUE TITLE
Consider not using Bootstrap

### ISSUE THREAD

**Issue by zautumnz** [prolesoft/MarXXIsts-Python#5]
Bootstrap is extremely large (156kb minified, about 25k gzipped), heavy handed, and pretty much means the site is going to look like Bootstrap. There are a bunch of smaller options that don't get in the way as much, like [these](https://github.com/troxler/awesome-css-frameworks#very-lightweight), that we could maybe switch to instead.

**Comment by aeshthetic** [comment]
I went with bootstrap just so it wouldn't look ugly right off the bat; I'm totally open to alternatives and have no reason to stick to bootstrap going forward.

That being said, I wouldn't like to worry too much about looks right now personally, although you're more than welcome to make any changes that you find appropriate!

**Comment by zautumnz** [comment]
Closing since this isn't really vital, and we both know Bootstrap. As things progress it might make sense to swap out or build a regular client SPA, but that's the future.
